// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package webshop

import (
	"webshop/internal/config"
	"webshop/internal/database"
	"webshop/shop/boundary"
	"webshop/shop/control"
)

// Injectors from wire.go:

func Initialize() *AppContext {
	configConfig := config.ProvideConfig()
	db := database.ProvideDatabase(configConfig)
	productRepository := boundary.ProvideSqlxRepository(db)
	productController := control.ProvideController(productRepository)
	router := boundary.ProvideRouter(productController)
	appContext := &AppContext{
		Router: router,
	}
	return appContext
}

// wire.go:

type AppContext struct {
	boundary.Router
}
