openapi: 3.0.0
info:
  title: product REST API
servers:
  - url: http://localhost:8000
    description: local development server
paths:
  /v1/product:
    post:
      description: insert a new product
      operationId: CreateProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductBase'
      responses:
        201:
          description: product successfully inserted
        400:
          description: validation failed

components:
  schemas:
    ProductBase:
      properties:
        title:
          type: string
          description: title of the product
        description:
          type: string
          description: description of the product
        price:
          type: integer
          description: price of the product
      required:
        - title
        - description
        - price